---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - source.yaml
  - secret-store.yaml
  - external-secrets.yaml
  - namespace.yaml
  - grafana
  - alloy
  - loki
  - mimir
